In [7]:
import tensorflow as tf
print("tensorFlow version:-",tf.__version__)

tensorFlow version:- 2.15.0


In [8]:
mnist=tf.keras.datasets.mnist
(X_train,y_train),(X_test,y_test)=mnist.load_data()
X_train,X_test=X_train/255.0,X_test/255.0

In [10]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [11]:
predictions=model(X_train[:1]).numpy()
predictions

array([[ 0.07686433,  0.5099632 , -0.80200344, -0.17737335,  0.1141607 ,
        -0.21010709,  1.1260883 , -0.2992844 ,  0.6228595 ,  0.2633129 ]],
      dtype=float32)

In [12]:
tf.nn.softmax(predictions).numpy()

array([[0.08337123, 0.12856083, 0.03462013, 0.06465501, 0.08653938,
        0.06257287, 0.23806106, 0.05723437, 0.14392588, 0.10045923]],
      dtype=float32)

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [14]:
loss_fn(y_train[:1], predictions).numpy()


2.7714233

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [17]:
model.fit(X_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.3003 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1446 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1090 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0885 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0758 - accuracy: 0.9761


In [19]:
model.evaluate(X_test,  y_test, verbose=2)


313/313 - 1s - loss: 0.0749 - accuracy: 0.9782 - 656ms/epoch - 2ms/step


[0.07486092299222946, 0.9782000184059143]

In [20]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [23]:
probability_model(X_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.36182509e-09, 1.02053683e-07, 6.80646338e-07, 6.12033764e-05,
        1.34714176e-11, 4.16532544e-07, 5.64613257e-14, 9.99937057e-01,
        5.23690638e-08, 5.58771717e-07],
       [2.06291126e-08, 7.29396939e-04, 9.99253809e-01, 1.62349079e-05,
        1.34702210e-12, 5.30884847e-07, 5.81946651e-08, 1.53331124e-13,
        2.81072534e-08, 9.70611327e-15],
       [3.33779980e-07, 9.96529758e-01, 7.18057854e-04, 3.45289845e-05,
        2.16275421e-05, 5.54231920e-05, 1.60446125e-05, 2.33923434e-03,
        2.83829373e-04, 1.21652670e-06],
       [9.99988317e-01, 1.40635850e-10, 9.26577002e-07, 1.35286768e-08,
        1.37149030e-07, 1.41179714e-06, 1.04450044e-06, 3.67200528e-06,
        2.09178244e-10, 4.38935740e-06],
       [1.24901135e-05, 1.41866572e-08, 1.32821276e-06, 1.58956325e-07,
        9.92338121e-01, 1.41940075e-06, 1.08351298e-06, 1.17290860e-04,
        7.31884825e-07, 7.52740400e-03]], dtype=float32)>